### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by Cedri4** [shiimizu/ComfyUI-TiledDiffusion#11]
I am on the portable version on Windows 11, and ComfyUI is fully updated.

The error in the terminal:

  Traceback (most recent call last):
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\__init__.py", line 1, in <module>
    from .tiled_diffusion import NODE_CLASS_MAPPINGS as TD_NCM, NODE_DISPLAY_NAME_MAPPINGS as TD_NDCM
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\tiled_diffusion.py", line 304
    >>>>>>> 195fed535d6a2cb01dc519e0f431a4325c65721a
              ^
SyntaxError: invalid decimal literal

Cannot import F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion module for custom nodes: invalid decimal literal (tiled_diffusion.py, line 304)
![image](https://github.com/shiimizu/ComfyUI-TiledDiffusion/assets/93396286/6381d410-74e4-46b7-842b-7441bc1f9a17)

**Comment by shiimizu** [comment]
Looks like something strange is in the source code of your copy?
Line 304 should like like:
https://github.com/shiimizu/ComfyUI-TiledDiffusion/blob/195fed535d6a2cb01dc519e0f431a4325c65721a/tiled_diffusion.py#L303-L305
Try reinstalling the node.

**Comment by Cedri4** [comment]
Weird I have like that 
![image](https://github.com/shiimizu/ComfyUI-TiledDiffusion/assets/93396286/1edabcfe-b75b-4b41-8a51-b659ef4ef043)

**Comment by Cedri4** [comment]
I will try reinstalling it

**Comment by Cedri4** [comment]
Thank you it's fixed!
