### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by ShionCox** [shiimizu/ComfyUI-TiledDiffusion#35]
Traceback (most recent call last):
  File "E:\ComfyUI_Max\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\__init__.py", line 1, in <module>
    from .tiled_diffusion import NODE_CLASS_MAPPINGS as TD_NCM, NODE_DISPLAY_NAME_MAPPINGS as TD_NDCM
  File "E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\tiled_diffusion.py", line 572, in <module>
    hook_all()
  File "E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 158, in hook_all
    hook_gligen__set_position(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 122, in hook_gligen__set_position
    fn = write_to_file_and_return_fn(Gligen._set_position, modified_source)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 232, in write_to_file_and_return_fn
    spec.loader.exec_module(module)
  File "E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\.patches.py", line 219
    nonlocal objs
IndentationError: unexpected indent

Cannot import E:\ComfyUI_Max\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion module for custom nodes: unexpected indent (.patches.py, line 219)

**Comment by shiimizu** [comment]
Fixed in the latest commit.
